name: Fresh MacOS Build Test

on:
  - push

jobs:
  test-master-script:
    name: Test master script
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: .dotfiles
      
      - name: Run install
        run: |
          echo $HOME
          ls -a
          cd .dotfiles
          sh fresh.sh
